# Generated by Django 4.2.3 on 2023-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mail_id',
            field=models.EmailField(max_length=40),
        ),
    ]
