# Generated by Django 4.2.3 on 2023-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_staff_date_ofjoin_staff_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept_name',
            field=models.CharField(blank=True, default='CSE', max_length=15),
        ),
    ]
