# Generated by Django 4.2.3 on 2023-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_staff_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
