# Generated by Django 4.2.3 on 2023-08-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_staff_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='staff_name',
            new_name='staff',
        ),
    ]
