# Generated by Django 4.2.3 on 2023-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_rename_staff_name_journals_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='name_journal',
        ),
        migrations.AddField(
            model_name='journals',
            name='journal_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
